title: YAPI.ae
subtitle: "YAP Centre For Blockchain Studies"
description: "The YAP Centre For Blockchain Studies(Dubai) is a think tank and research center which investigates
implications of blockchain technology for companies and their business models."
author: Yapi
language: en
timezone: UTC

url: http://yapae.github.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:yapAE/yapAE.github.io.git

highlight:
  enable: true
  line_number: false
disqus_shortname: yapi-1
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
facebook: yapi.ae
twitter: yapi.ae
wechat: yapAE
weibo: yapAE
github: yapAE/yapAE.github.io
