# theme.toml template for a Hugo theme
# See https://github.com/gohugoiox/hugoThemes#themetoml for an example

name = "Beyond Geek Guide"
license = "MIT"
licenselink = "https://github.com/imfing/hextra/blob/main/LICENSE"
description = "Beyond Geek Guide (B-GG.com) is your go-to hub for easy-to-follow tech tutorials, software guides, and practical tips. Whether you're a complete beginner or a tech enthusiast, we break down complex tools and concepts into simple, step-by-step guides. Our mission is to make technology accessible for everyone — so you can work smarter, stay secure, and explore the digital world with confidence."
homepage = "https://github.com/imfing/hextra/"
demosite = "https://imfing.github.io/hextra/"
tags = ["Modern", "Elegant", "Blog", "Documentation", "Responsive", "Clean", "Light", "Dark", "Minimal"]
features = ["Responsive", "Dark Mode", "Search", "Syntax Highlighting", "Multilingual", "Social", "Blog", "RSS", "Customization"]
min_version = "0.146.0"

[author]
  name = "Bgg"
  homepage = "https://b-gg.com"
